on:
    push:
        branches:
            - master
name: Deploy to Test Site
jobs:
    deployToTest:
        name: Deploy to Test Site
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Set Up Node
              uses: actions/setup-node@v1
              with:
                  node-version: "10.15"
            - run: npm run-script build-test

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: us-east-2
            - run: aws s3 cp /home/runner/work/sigl/sigl/dist/ s3://test.wim.usgs.gov/sigl/ --recursive

            - name: GitHub Action for Slack
              uses: Ilshidur/action-slack@a6d9e9ed519555c498265694cf2d7367d9dc6926
              env:
                  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
              with:
                  args: ":success: Successfully deployed to test.wim.usgs.gov/sigl/ :test:"
